# Generated by Django 5.2.12 on 2026-03-19 09:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('locations', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Alert',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('disaster_type', models.CharField(choices=[('Flood', 'Flood'), ('Fire', 'Fire'), ('Conflict', 'Conflict'), ('Disease Outbreak', 'Disease'), ('Drought', 'Drought'), ('Landslide', 'Landslide'), ('Other', 'Other')], max_length=64)),
                ('severity', models.PositiveSmallIntegerField(choices=[(1, 'Low'), (2, 'Moderate'), (3, 'High'), (4, 'Extreme'), (5, 'Catastrophic')], default=2)),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True, default='')),
                ('status', models.CharField(choices=[('New', 'New'), ('Verified', 'Verified'), ('Resolved', 'Resolved'), ('Dismissed', 'Dismissed')], default='New', max_length=32)),
                ('source', models.CharField(blank=True, default='Community', max_length=128)),
                ('occurred_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('location', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='alerts', to='locations.location')),
            ],
            options={
                'indexes': [models.Index(fields=['disaster_type', 'severity'], name='alerts_aler_disaste_86cf38_idx'), models.Index(fields=['status', 'created_at'], name='alerts_aler_status_bbfb4b_idx'), models.Index(fields=['created_at'], name='alerts_aler_created_8af5ce_idx')],
            },
        ),
    ]
