# Generated by Django 5.2.12 on 2026-03-19 09:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('alerts', '0001_initial'),
        ('locations', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Report',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reporter_name', models.CharField(blank=True, default='', max_length=160)),
                ('reporter_phone', models.CharField(blank=True, default='', max_length=32)),
                ('description', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('alert', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='reports', to='alerts.alert')),
                ('location', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='reports', to='locations.location')),
            ],
            options={
                'indexes': [models.Index(fields=['created_at'], name='reports_rep_created_a6aabf_idx')],
            },
        ),
    ]
