# Generated by Django 5.2.12 on 2026-03-19 09:01

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Location',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('state', models.CharField(choices=[('Central Equatoria', 'Central Equatoria'), ('Eastern Equatoria', 'Eastern Equatoria'), ('Western Equatoria', 'Western Equatoria'), ('Jonglei', 'Jonglei'), ('Lakes', 'Lakes'), ('Northern Bahr el Ghazal', 'Northern Bahr El Ghazal'), ('Western Bahr el Ghazal', 'Western Bahr El Ghazal'), ('Unity', 'Unity'), ('Upper Nile', 'Upper Nile'), ('Warrap', 'Warrap')], max_length=64)),
                ('county', models.CharField(blank=True, default='', max_length=128)),
                ('payam', models.CharField(blank=True, default='', max_length=128)),
                ('boma', models.CharField(blank=True, default='', max_length=128)),
                ('latitude', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ('longitude', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'indexes': [models.Index(fields=['state', 'county'], name='locations_l_state_5254e9_idx')],
            },
        ),
    ]
